# Generated by Django 4.0.2 on 2022-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('description', models.CharField(max_length=140)),
                ('serial', models.IntegerField()),
                ('indicator1', models.IntegerField()),
                ('indicator2', models.IntegerField()),
                ('indicator3', models.IntegerField()),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
    ]
