# Generated by Django 4.0.2 on 2022-02-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='serial',
            field=models.CharField(max_length=64),
        ),
    ]
