# Generated by Django 4.0.2 on 2022-02-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolve',
            field=models.CharField(default='', max_length=140),
        ),
    ]
