# Generated by Django 4.0.2 on 2022-02-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_rename_resolve_issue_response_issue_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='indicator1',
            field=models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('blinking', 'Blinking')], default='off', max_length=8),
        ),
        migrations.AlterField(
            model_name='issue',
            name='indicator2',
            field=models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('blinking', 'Blinking')], default='off', max_length=8),
        ),
        migrations.AlterField(
            model_name='issue',
            name='indicator3',
            field=models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('blinking', 'Blinking')], default='off', max_length=8),
        ),
    ]
