# Generated by Django 4.0.2 on 2022-02-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_indicator1_alter_issue_indicator2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='uid',
            field=models.PositiveIntegerField(),
        ),
    ]
