# Generated by Django 4.0.2 on 2022-02-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issue_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='response',
            field=models.CharField(default=None, max_length=140),
        ),
    ]
