# Generated by Django 4.0.2 on 2022-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_alter_issue_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='response',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
