# Generated by Django 4.1.3 on 2023-03-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_issue_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
