# Generated by Django 4.1.3 on 2023-03-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0009_delete_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=140)),
                ('serial', models.CharField(max_length=64)),
                ('indicator1', models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('blinking', 'Blinking')], default='off', max_length=8)),
                ('indicator2', models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('blinking', 'Blinking')], default='off', max_length=8)),
                ('indicator3', models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('blinking', 'Blinking')], default='off', max_length=8)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
    ]
