version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile1
    env_file: venv/.env
    restart: always
    volumes:
      - .:/app/
    depends_on:
      - db
    working_dir: "/app"
    expose:
      - 8000
    ports:
      - "8000:8000"
    #command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    build:
      context: .
      dockerfile: .docker/Dockerfile1
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    env_file: venv/.env
    ports:
      - "3306:3306"

volumes:
  mysql_data:
