version: "3.8"

services:

  backend:
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile
    entrypoint: [ "/wait.sh" ]
    depends_on: #links:
      - db
    working_dir: "/app"
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    expose:
      - 8000
  #    command: python manage.py runserver 0.0.0.0:8000

  db:
    container_name: rooj-proj-db
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    restart: always
    env_file: .docker/.env
    #environment:
    #  MYSQL_ROOT_PASSWORD: mysql-root-password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  front:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile_vue
    depends_on:
      - backend
    working_dir: "/vue_front"
    volumes:
      - .:/front_vue
    ports:
      - "8080:8080"
    expose:
      - 8080

